### ISSUE TITLE
Failed to activate the rust-api-docs-helper package

### ISSUE THREAD

**Issue by lalawuu** [plafue/rust-api-docs-helper#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.2
**Thrown From**: [rust-api-docs-helper](https://github.com/plafue/rust-api-docs-helper) package, v0.5.1
### Stack Trace

Failed to activate the rust-api-docs-helper package

```
At Tried to create a gutter with a name that is already in use.

Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:28:15)
  at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:481:35)
  at /Users/bisunday/.atom/packages/rust-api-docs-helper/lib/rust-api-docs-helper.coffee:41:18
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
  at Object.module.exports.RustApiDocsHelper.activate (/Users/bisunday/.atom/packages/rust-api-docs-helper/lib/rust-api-docs-helper.coffee:39:22)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:303:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:252:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:58.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:58.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:58.1.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:56.4.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:54.7.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:52.9.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:50.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:26.2.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:25.4.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:25.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  4x -0:20.9.0 rust-api-docs-helper:trigger (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:18.6.0 settings-view:open (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:15.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "rust-api-docs-helper": {
    "useInternalBrowser": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v0.4.1
javascript-snippets, v1.0.0
jsformat, v0.8.1
language-cmake, v0.1.3
language-rust, v0.4.3
linter-rust, v0.1.0
racer, v0.11.0
rust-api-docs-helper, v0.5.1
script, v2.23.0
vim-mode, v0.49.0
vim-surround, v0.6.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by Doaxan** [comment]
+1
