### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by imp** [plafue/rust-api-docs-helper#14]
Got this when running formatting (atom-beautify)

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [rust-api-docs-helper](https://github.com/plafue/rust-api-docs-helper) package 0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/imp/.atom/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22

TypeError: Cannot read property 'length' of undefined
    at GutterDecorator.module.exports.GutterDecorator.updateMarkers (/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22:7)
    at /packages/rust-api-docs-helper/lib/gutter-decorator.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1571:26)
    at later (/usr/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:21:13)
```

### Commands

```
     -0:14.5.0 atom-beautify:beautify-editor (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atomatigit 1.5.5 
autocomplete-python 1.10.0 
browser-plus 0.0.98 
build 0.68.0 
build-cargo 2.0.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
imdone-atom 2.2.6 
imdone-atom-github 0.1.11 
intentions 1.1.5 
language-diff 0.7.0 
language-docker 1.1.8 
language-rust 0.4.12 
linter 2.2.0 
linter-pycodestyle 2.0.2 
linter-rust 0.8.0 
linter-ui-default 1.6.3 
merge-conflicts 1.4.5 
minimap 4.29.3 
minimap-git-diff 4.3.1 
project-manager 3.3.5 
python-tools 0.6.9 
racer 0.20.0 
release-notes 0.53.0 
rust-api-docs-helper 0.5.1 
rusty-dark-syntax 0.7.0 
split-diff 1.4.3 
sync-settings 0.8.2 
tool-bar 1.1.0 
travis-ci-status 1.3.1 
```

**Comment by yao2007** [comment]
same problem. I have no idea to fix it

**Comment by fztfztfztfzt** [comment]
I have the same problem.

**Comment by wolfadex** [comment]
This is also an issue with:
**Atom:** 1.23.3 x64
**OS:** OS X 10.11.6

**Comment by wired-R** [comment]
I have the same problem.
