### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Candlend** [plafue/rust-api-docs-helper#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [rust-api-docs-helper](https://github.com/plafue/rust-api-docs-helper) package 0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/candle/.atom/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22

TypeError: Cannot read property 'length' of undefined
    at GutterDecorator.module.exports.GutterDecorator.updateMarkers (/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22:7)
    at /packages/rust-api-docs-helper/lib/gutter-decorator.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1694:26)
    at later (/usr/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -1:45 core:move-right (input.hidden-input)
     -1:42 core:backspace (input.hidden-input)
     -1:24.4.0 core:paste (input.hidden-input)
     -1:23.5.0 core:undo (input.hidden-input)
     -1:19.6.0 core:paste (input.hidden-input)
  4x -1:18.6.0 core:backspace (input.hidden-input)
     -1:14 core:confirm (input.hidden-input)
     -1:02.7.0 core:backspace (input.hidden-input)
     -1:01.8.0 core:confirm (input.hidden-input)
     -0:44.5.0 key-binding-resolver:toggle (input.hidden-input)
     -0:41.6.0 rust-api-docs-helper:trigger (input.hidden-input)
  4x -0:33.5.0 intentions:highlight (input.hidden-input)
     -0:24.1.0 key-binding-resolver:toggle (input.hidden-input)
     -0:21 intentions:highlight (input.hidden-input)
     -0:20.7.0 core:undo (input.hidden-input)
  3x -0:14 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-ide-ui 0.5.2 
atom-language-rust 0.12.3 
atom-python-run 0.9.3 
atom-runner 2.7.1 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
build 0.69.0 
build-cargo 2.0.0 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.13 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
incremental-search 5.2.2 
intentions 1.1.5 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-pigments 0.2.2 
platformio-ide-terminal 2.7.0 
racer 0.20.0 
rust-api-docs-helper 0.5.1 
simplified-chinese-menu 5.3.4 
sync-settings 0.8.3 
tokamak 0.4.1 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
web-search 0.3.3 
```

**Comment by joepie91** [comment]
[Enter steps to reproduce:]

1. Save a `.rs` file

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: linux 4.9.76
**Thrown From**: [rust-api-docs-helper](https://github.com/plafue/rust-api-docs-helper) package 0.5.1


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/sven/.atom/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22

TypeError: Cannot read property 'length' of undefined
    at GutterDecorator.module.exports.GutterDecorator.updateMarkers (/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22:7)
    at /packages/rust-api-docs-helper/lib/gutter-decorator.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/nix/store/s0ig009mr1q6nx62iyg055mmaxqp7ha3-atom-1.23.2/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/nix/store/s0ig009mr1q6nx62iyg055mmaxqp7ha3-atom-1.23.2/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/nix/store/s0ig009mr1q6nx62iyg055mmaxqp7ha3-atom-1.23.2/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1699:26)
    at later (/nix/store/s0ig009mr1q6nx62iyg055mmaxqp7ha3-atom-1.23.2/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:23.9.0 intentions:highlight (input.hidden-input)
     -0:23.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
api-docs 0.0.6 
atom-jade 0.3.0 
atom-like-brackets-editor 1.2.0 
atom-ternjs 0.18.3 
atomatigit 1.5.5 
auto-detect-indentation 1.3.0 
autocomplete-glsl 0.2.3 
autocomplete-modules 1.8.0 
better-window-title 1.0.3 
busy-signal 1.4.3 
clear-syntax 0.6.0 
color-picker 2.2.5 
dark-flat-ui 1.2.4 
disable-keybindings 0.6.0 
git-control 0.9.0 
git-line 0.6.0 
git-time-machine 1.5.9 
glacier-dark-ui 0.5.0 
glsl-preview 1.4.1 
intentions 1.1.5 
isotope-ui 2.8.5 
jumpy 4.2.0 
keyboard-scroll 0.7.0 
language-assembly 0.7.2 
language-bison-flex 0.3.1 
language-diff 0.7.0 
language-glsl 2.0.4 
language-jade 0.7.2 
language-markdown 0.25.1 
language-pegjs 0.5.0 
language-pug 0.0.18 
language-rust 0.4.12 
language-x86-64-assembly 2.2.11 
language-x86asm 0.9.0 
linter 2.2.0 
linter-glsl 2.1.4 
linter-ui-default 1.6.10 
monokai-blackboard 0.3.0 
monokai-dark 1.3.0 
monokai-shade-src 0.3.4 
monokai-soda 1.2.0 
nix 2.1.0 
one-dark-mini-ui 2.0.5 
one-dark-shade-ui 0.1.0 
quick-highlight 0.12.0 
rainbow-tabs 2.5.1 
rust-api-docs-helper 0.5.1 
rustsym 0.4.1 
slim-dark-ui 0.12.0 
snow-dark-syntax 0.1.1 
source-preview 0.5.3 
source-preview-babel 0.2.1 
source-preview-markdown 0.1.1 
source-preview-pug 0.2.0 
stripper-syntax 0.0.0 
tree-view-open-files 0.3.0 
wakatime 7.0.4 
webbox-color 0.5.9 
zentabs 0.8.9 
```
