### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by U007D** [plafue/rust-api-docs-helper#20]
[Enter steps to reproduce:]

1. Open Rust project
2. Start a [Teletype](https://teletype.atom.io/) multi-user session with 1 other person
3. Dozens of these errors line the right side of the screen.

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.6
**Thrown From**: [rust-api-docs-helper](https://github.com/plafue/rust-api-docs-helper) package 0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/bRad/.atom/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22

TypeError: Cannot read property 'length' of undefined
    at GutterDecorator.module.exports.GutterDecorator.updateMarkers (/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22:7)
    at /packages/rust-api-docs-helper/lib/gutter-decorator.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1724:26)
    at later (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -3:53.5.0 core:move-left (input.hidden-input)
     -3:53.3.0 core:move-down (input.hidden-input)
  2x -3:46.8.0 core:backspace (input.hidden-input)
     -3:39.5.0 editor:newline (input.hidden-input)
     -3:33.4.0 core:backspace (input.hidden-input)
     -3:24.3.0 core:move-up (input.hidden-input)
  2x -3:10.1.0 editor:newline (input.hidden-input)
     -2:20.7.0 core:move-left (input.hidden-input)
     -2:00.3.0 core:backspace (input.hidden-input)
  2x -1:59.4.0 editor:newline (input.hidden-input)
  8x -1:50.5.0 core:backspace (input.hidden-input)
     -1:40.8.0 autocomplete-plus:confirm (input.hidden-input)
  8x -1:28.1.0 core:backspace (input.hidden-input)
     -1:20.8.0 editor:newline (input.hidden-input)
  3x -0:24.6.0 core:backspace (input.hidden-input)
     -0:22.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.3 
atom-terminal 0.8.0 
fonts 3.0.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
ide-rust 0.15.0 
language-rust 0.4.12 
minimap 4.29.8 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
pigments 0.40.2 
rust-api-docs-helper 0.5.1 
teletype 0.10.0 
terminal-status 1.6.8 
vim-mode-plus 1.30.0 
```

**Comment by kunzeal** [comment]
same issue
