### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kahasta** [plafue/rust-api-docs-helper#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 3.1.6
**OS**: "Manjaro Linux"
**Thrown From**: [rust-api-docs-helper](https://github.com/plafue/rust-api-docs-helper) package 0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/kahasta/.atom/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22

TypeError: Cannot read property 'length' of undefined
    at GutterDecorator.module.exports.GutterDecorator.updateMarkers (/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22:7)
    at /packages/rust-api-docs-helper/lib/gutter-decorator.coffee:1:1
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at TextBuffer.emitDidStopChangingEvent (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:2381:18)
    at later (/usr/lib/atom/node_modules/text-buffer/lib/helpers.js:18:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-go-jump-test 1.2.0 
atom-ide-ui 0.13.0 
atom-language-rust 0.14.1 
atom-runner 2.7.1 
atom-rust 0.1.1 
build-cargo 2.0.0 
busy-signal 2.0.1 
go-build 0.2.2 
go-debug 1.6.2 
go-formatter 0.0.2 
go-imports 0.2.0 
go-outline 0.6.11 
go-plus 6.1.0 
go-postfix 0.3.0 
go-quick-import 0.3.1 
go-signature-statusbar 1.2.3 
go-snippets 0.5.1 
go-tip 2.4.0 
go-types 1.2.1 
ide-go 0.12.3 
ide-golang 0.0.5 
ide-rust 0.20.0 
intentions 1.1.5 
json-to-go-struct 0.0.5 
language-go-mentor 0.1.0 
language-rust 0.4.12 
language-rust-redux 0.3.3 
linter 2.3.0 
linter-patch-errors-singleline 1.0.1 
linter-rust 1.0.1 
linter-rust-cargo 1.1.0 
linter-spell 0.15.0 
linter-spell-go 0.2.0 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.9.1 
racer-plus 2.0.0 
racer-v2 2.2.1 
rust-api-docs-helper 0.5.1 
rust-doc-viewer 2.6.3 
rust-lang 0.6.0 
rustfmt 0.1.3 
rustsym 0.4.1 
terminal-plus 0.14.5 
```

**Comment by IngmarBitter** [comment]
Same problem for me on first time install of Atom 1.36.1 x64, rustc 1.34.1 (fc50f328b 2019-04-24)
with rust hello_world/main.rs:
fn main() {
    println!("Hello, world!");
}

happens with every letter typed.

C:\Users\ingmar\.atom\packages\rust-api-docs-helper\lib\gutter-decorator.coffee:22
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at GutterDecorator.module.exports.GutterDecorator.updateMarkers (file:///C:/Users/../.atom/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:22:7)
    at file:///C:/Users/../.atom/packages/rust-api-docs-helper/lib/gutter-decorator.coffee:1:1
    at Function.simpleDispatch (C:\Users\..\AppData\Local\atom\app-1.36.1\resources\app\static\<embedded>:11:1172164)
    at Emitter.emit (C:\Users\..\AppData\Local\atom\app-1.36.1\resources\app\static\<embedded>:11:1173605)
    at TextBuffer.emitDidStopChangingEvent (C:\Users\..\AppData\Local\atom\app-1.36.1\resources\app\static\<embedded>:11:504894)
    at later (C:\Users\..\AppData\Local\atom\app-1.36.1\resources\app\static\<embedded>:14:98352)
